### ISSUE TITLE
Fix link to jar file

### ISSUE THREAD

**Issue by mclaeysb** [meyskens/nokia-irail#3]
Hi

I tried to download the compiled code from the link in the readme but it didn't work. http://nokia.maartje.dev/iRail.jar

Looking forward to test this on my Nokia 112!

**Comment by meyskens** [comment]
What error are you getting?

**Comment by mclaeysb** [comment]
The download simply never starts

**Comment by meyskens** [comment]
Tested this on several devices and this works fine for me

**Comment by mclaeysb** [comment]
Didn't work on Chrome but worked on Firefox. No idea why. Sorry to bother, thanks for the help. I'll let you know if it works!

**Comment by mclaeysb** [comment]
Working superfine on my Nokia 112! This is awesome!!

(I'm getting an exception 'space in url' when I enter location names with spaces, but that's all).

**Comment by meyskens** [comment]
That could be, J2ME probably does not escape URLs by default. PRs welcome!
